version: "3.8"

services:
  db:
    image: postgres:15
    container_name: educacao_db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: educacao
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build:
      context: ./backend
    container_name: educacao_api
    ports:
      - "3000:3000"
    depends_on:
      - db
    volumes:
      - ./backend:/app
    environment:
      DATABASE_URL: postgresql://root:root@db:5432/educacao
    command: sh -c "/wait-for-it.sh db:5432 -- npx prisma migrate dev --name init && npm run dev"

  frontend:
    build:
      context: ./frontend
      target: dev
    container_name: educacao_frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./frontend/.env
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm run dev

volumes:
  pgdata:
